### ISSUE TITLE
possible tagged release

### ISSUE THREAD

**Issue by sadlerm4** [chocolateimage/fontviewer#4]
hello! i packaged this amazing application in terra - a high quality third-party repository for fedora(-based) distros, around the time when you posted about fontviewer on reddit. i use cinnamon primarily so it's so great that you've made a gtk font viewer that looks cohesive with DEs other than GNOME.

i wasn't expecting active development on the repo after june but it's really cool that you're still working on stuff:) just so it's a bit easier for me to consider packaging going forward, are you planning on tagging a release perhaps in future? the package is currently built from latest commit which i've had to pause due to potential breaking changes (naturally)

happy holidays/merry christmas and thanks again for creating fontviewer!

**Comment by chocolateimage** [comment]
I created the tag "v1.1.0" now and am planning to create more tags when future updates come! https://github.com/chocolateimage/fontviewer/tags

also note that the v1.1.0 tag requires a new data file (for the Google icon) that the correct locations can be seen at meson.build
